src/AppSemTemplate/Controllers/DiLifeCyCleController.cs
using AppSemTemplate.Services;
using Microsoft.AspNetCore.Mvc;

namespace AppSemTemplate.Controllers
{
    [Route("teste-di")]
    public class DiLifeCycleController : Controller
    {
        public OperacaoService OperacaoService { get; private set; }
        public OperacaoService OperacaoService2 { get; private set; }
        public IServiceProvider ServiceProvider { get; private set; }

        public DiLifeCycleController(OperacaoService operacaoService,
                                     OperacaoService operacaoService2,
                                     IServiceProvider serviceProvider)
        {
            OperacaoService = operacaoService;
            OperacaoService2 = operacaoService2;
            ServiceProvider = serviceProvider;
        }

        public string Index()
        {
            return
                "Primeira instância: " + Environment.NewLine +
                OperacaoService.Transient.OperacaoId + Environment.NewLine +
                OperacaoService.Scoped.OperacaoId + Environment.NewLine +
                OperacaoService.Singleton.OperacaoId + Environment.NewLine +
                OperacaoService.SingletonInstance.OperacaoId + Environment.NewLine +

                Environment.NewLine + Environment.NewLine +

                "Segunda instância: " + Environment.NewLine +
                OperacaoService2.Transient.OperacaoId + Environment.NewLine +
                OperacaoService2.Scoped.OperacaoId + Environment.NewLine +
                OperacaoService2.Singleton.OperacaoId + Environment.NewLine +
                OperacaoService2.SingletonInstance.OperacaoId + Environment.NewLine;
        }

        [Route("teste")]
        public string Teste([FromServices] OperacaoService operacaoService3)
        {
            return
                operacaoService3.Transient.OperacaoId + Environment.NewLine +
                operacaoService3.Scoped.OperacaoId + Environment.NewLine +
                operacaoService3.Singleton.OperacaoId + Environment.NewLine +
                operacaoService3.SingletonInstance.OperacaoId;
        }


        [Route("view")]
        public IActionResult TesteView()
        {
            return View("Index");
        }

        [Route("container")]
        public string TesteContainer()
        {
            using (var serviceScope = ServiceProvider.CreateScope())
            {
                var services = serviceScope.ServiceProvider;

                var singService = services.GetRequiredService<IOperacaoSingleton>();

                return "Instância Singleton: " + Environment.NewLine +
                        singService.OperacaoId + Environment.NewLine;
            }
        }
    }
}

src/AppSemTemplate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppSemTemplate</title>
    <script type="importmap"></script>

    @* Desenvolvimento *@
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    </environment>

    @* Produção *@
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <header>
        @* Navegação *@
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppSemTemplate</a>
                @* Botão toggle *@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @* Itens de menu *@
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @* Conteúdo principal *@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @* Rodapé *@
    <footer class="border-top footer text-muted">
        <div class="container">
            Seu site ASP.NET feito do jeito certo.
        </div>
    </footer>

    @* Scripts *@
    @* Desenvolvimento *@
    <environment include="Development">
        <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
        <script src="~/js/site.js"></script>
        <script src="~/js/cep.js"></script>
    </environment>
    @* Produção *@
    <environment exclude="Development">
        <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.min.js"></script>
    </environment>

    @* Renderiza a seção Scripts da view carregadada *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/AppSemTemplate/Views/Shared/_LayoutFull.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppSemTemplate</title>
    <script type="importmap"></script>

    @* Desenvolvimento *@
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>

    @* Produção *@
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" />
    </environment>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        @* Navegação *@
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Layout Novo</a>
                @* Botão toggle *@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @* Itens de menu *@
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Vendas" asp-controller="Gestao" asp-action="Index">Gestão de Vendas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Produtos" asp-controller="Cadastro" asp-action="Index">Gestão de Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="DiLifeCycle" asp-action="Index">Teste DI</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    @* Conteúdo principal *@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @* Rodapé *@
    <footer class="border-top footer text-muted">
        <div class="container">
            Seu site ASP.NET feito do jeito certo.
        </div>
    </footer>

    @* Scripts *@
    @* Desenvolvimento *@
    <environment include="Development">
        <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
        <script src="~/js/site.js"></script>
        <script src="~/js/cep.js"></script>
    </environment>
    @* Produção *@
    <environment exclude="Development">
        <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.min.js"></script>
    </environment>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>